declare module 'bun' {
  interface Env {
    CLERK_SECRET_KEY: string
    CLERK_SIGNING_SECRET: string
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: string
    NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: string
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: string
    NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: string

    DATABASE_URL: string

    UPSTASH_REDIS_REST_URL: string
    UPSTASH_REDIS_REST_TOKEN: string
  }
}
